from __future__ import annotations

# AIDEV-NOTE: data, not code — measured coverage lives in spike/gate0.md

# CloudControl types that can be listed without ResourceModel (no required parent IDs)
CURATED_TYPES: tuple[str, ...] = (
    "AWS::S3::Bucket",
    "AWS::EC2::VPC",
    "AWS::EC2::Subnet",
    "AWS::EC2::SecurityGroup",
    "AWS::EC2::Instance",
    "AWS::EC2::Volume",
    "AWS::EC2::InternetGateway",
    "AWS::EC2::NatGateway",
    "AWS::EC2::RouteTable",
    "AWS::EC2::EIP",
    "AWS::EC2::KeyPair",
    "AWS::EC2::LaunchTemplate",
    "AWS::EC2::VPCEndpoint",
    "AWS::EC2::TransitGateway",
    "AWS::IAM::Role",
    "AWS::IAM::User",
    "AWS::IAM::Group",
    "AWS::IAM::ManagedPolicy",
    "AWS::IAM::OIDCProvider",
    "AWS::IAM::SAMLProvider",
    "AWS::IAM::InstanceProfile",
    "AWS::Lambda::Function",
    "AWS::DynamoDB::Table",
    "AWS::RDS::DBInstance",
    "AWS::RDS::DBCluster",
    "AWS::RDS::DBSubnetGroup",
    "AWS::RDS::DBParameterGroup",
    "AWS::ElastiCache::CacheCluster",
    "AWS::ElastiCache::ReplicationGroup",
    "AWS::SQS::Queue",
    "AWS::SNS::Topic",
    "AWS::KMS::Key",
    "AWS::KMS::Alias",
    "AWS::SecretsManager::Secret",
    "AWS::SSM::Parameter",
    "AWS::CloudFormation::Stack",
    "AWS::CloudWatch::Alarm",
    "AWS::Logs::LogGroup",
    "AWS::Events::Rule",
    "AWS::Events::EventBus",
    "AWS::ECR::Repository",
    "AWS::ECS::Cluster",
    "AWS::EKS::Cluster",
    "AWS::ElasticLoadBalancingV2::LoadBalancer",
    "AWS::ElasticLoadBalancingV2::TargetGroup",
    "AWS::AutoScaling::AutoScalingGroup",
    "AWS::Route53::HostedZone",
    "AWS::CloudFront::Distribution",
    "AWS::ApiGateway::RestApi",
    "AWS::ApiGatewayV2::Api",
    "AWS::StepFunctions::StateMachine",
    "AWS::Kinesis::Stream",
    "AWS::KinesisFirehose::DeliveryStream",
    "AWS::Athena::WorkGroup",
    "AWS::Backup::BackupVault",
    "AWS::EFS::FileSystem",
    "AWS::CodeBuild::Project",
    "AWS::CodePipeline::Pipeline",
    "AWS::Cognito::UserPool",
    "AWS::ACM::Certificate",
    "AWS::CertificateManager::Certificate",
    "AWS::Config::ConfigRule",
    "AWS::CloudTrail::Trail",
    "AWS::GuardDuty::Detector",
    "AWS::SecurityHub::Hub",
    "AWS::Redshift::Cluster",
    "AWS::OpenSearchService::Domain",
    "AWS::MSK::Cluster",
    "AWS::EC2::VPNConnection",
    "AWS::EC2::NetworkAcl",
    "AWS::EC2::NetworkInterface",
    "AWS::EC2::FlowLog",
    "AWS::EC2::VPCPeeringConnection",
)

# Types that are global (collected only in first region)
GLOBAL_TYPES: frozenset[str] = frozenset(
    {
        "AWS::IAM::Role",
        "AWS::IAM::User",
        "AWS::IAM::Group",
        "AWS::IAM::ManagedPolicy",
        "AWS::IAM::OIDCProvider",
        "AWS::IAM::SAMLProvider",
        "AWS::IAM::InstanceProfile",
        "AWS::Route53::HostedZone",
        "AWS::CloudFront::Distribution",
    }
)
